elastic:
  search:
    url: http://localhost:9200
sleepingpill:
   base:
     url: https://sleepingpill.javazone.no/public/
resttemplate:
  timeout:
    connectionRequestMs: 10000
    connectionMs: 10000
    readMs: 10000

logging:
  level:
    root: INFO
    no.java: TRACE